-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "password_hash" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "date_of_birth" TIMESTAMP(3),
    "phone" TEXT,
    "address" TEXT,
    "city" TEXT,
    "postcode" TEXT,
    "emergency_contact_name" TEXT,
    "emergency_contact_phone" TEXT,
    "account_status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Studio" (
    "id" TEXT NOT NULL,
    "studio_name" TEXT NOT NULL DEFAULT 'Hall of Mirrors Tattoo',
    "address" TEXT NOT NULL,
    "postcode" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "hours_monday_start" TEXT,
    "hours_monday_end" TEXT,
    "hours_tuesday_start" TEXT,
    "hours_tuesday_end" TEXT,
    "hours_wednesday_start" TEXT,
    "hours_wednesday_end" TEXT,
    "hours_thursday_start" TEXT,
    "hours_thursday_end" TEXT,
    "hours_friday_start" TEXT,
    "hours_friday_end" TEXT,
    "hours_saturday_start" TEXT,
    "hours_saturday_end" TEXT,
    "hours_sunday_start" TEXT,
    "hours_sunday_end" TEXT,
    "deposit_amount_fixed" DECIMAL(10,2),
    "deposit_percentage" DECIMAL(5,2),
    "cancellation_policy_hours" INTEGER NOT NULL DEFAULT 24,
    "about_section" TEXT,
    "instagram_handle" TEXT,
    "facebook_url" TEXT,
    "tiktok_handle" TEXT,
    "council_registration_ref" TEXT,
    "hepatitis_b_vaccination_date" TIMESTAMP(3),
    "professional_body_membership" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Booking" (
    "id" TEXT NOT NULL,
    "studio_id" TEXT NOT NULL,
    "artist_id" TEXT,
    "user_id" TEXT,
    "guest_email" TEXT,
    "guest_name" TEXT,
    "guest_phone" TEXT,
    "booking_reference" TEXT NOT NULL UNIQUE,
    "appointment_date_time" TIMESTAMP(3) NOT NULL,
    "estimated_duration_minutes" INTEGER NOT NULL DEFAULT 120,
    "appointment_status" TEXT NOT NULL DEFAULT 'pending_consent',
    "tattoo_type" TEXT NOT NULL DEFAULT 'new_tattoo',
    "tattoo_description" TEXT,
    "placement" TEXT,
    "estimated_size" TEXT,
    "color_or_bw" TEXT,
    "artist_notes" TEXT,
    "design_approved" BOOLEAN NOT NULL DEFAULT false,
    "deposit_amount" DECIMAL(10,2) NOT NULL,
    "deposit_paid" BOOLEAN NOT NULL DEFAULT false,
    "deposit_payment_method" TEXT,
    "deposit_paid_date" TIMESTAMP(3),
    "final_price_estimate" DECIMAL(10,2),
    "final_price_paid" DECIMAL(10,2),
    "final_payment_method" TEXT,
    "balance_due" DECIMAL(10,2) NOT NULL,
    "cancellation_reason" TEXT,
    "cancellation_initiated_by" TEXT,
    "cancellation_date" TIMESTAMP(3),
    "refund_issued" BOOLEAN NOT NULL DEFAULT false,
    "refund_amount" DECIMAL(10,2),
    "client_no_show" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "ConsultationRequest" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "tattoo_idea" TEXT NOT NULL,
    "preferred_contact_method" TEXT,
    "preferred_timeframe" TEXT,
    "consultation_status" TEXT NOT NULL DEFAULT 'new',
    "assigned_to" TEXT,
    "assigned_date" TIMESTAMP(3),
    "response_date" TIMESTAMP(3),
    "response_message" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ContactFormSubmission" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "submission_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "response_status" TEXT NOT NULL DEFAULT 'new',
    "responded_by" TEXT,
    "response_date" TIMESTAMP(3),
    "response_text" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "Booking_user_id_idx" ON "Booking"("user_id");
